import type { Equipment, MaintenanceRequest, User, Team, EquipmentCategory, Site, Area, WorkCenter, AutomationRule } from '../types';

export const mockTeams: Team[] = [
    { id: 't1', name: 'Internal Maintenance', memberIds: ['u2'], description: 'Heavy machinery and hydraulics' }, // Updated Name
    { id: 't2', name: 'Electronics', memberIds: ['u2'], description: 'Circuit boards and sensors' },
    { id: 't3', name: 'IT Support', memberIds: [], description: 'Computers and networks' },
    { id: 't4', name: 'Mechanical Titans', memberIds: ['u1', 'u2'], description: 'Elite response team' }, // Added for demo
];

export const mockSites: Site[] = [
    { id: 's1', name: 'Surat Finefab', type: 'Textile Plant', location: 'Surat, Gujarat' },
    { id: 's2', name: 'Gujarat AutoWorks', type: 'Automotive Assembly', location: 'Sanand, Gujarat' },
];

export const mockAreas: Area[] = [
    { id: 'a1', siteId: 's1', name: 'Weaving Shed' },
    { id: 'a2', siteId: 's2', name: 'Production Hall' },
];

export const mockWorkCenters: WorkCenter[] = [
    { id: 'wc1', areaId: 'a1', name: 'Loom Line A' },
    { id: 'wc2', areaId: 'a2', name: 'CNC Assembly Line' },
    { id: 'wc3', areaId: 'a2', name: 'Robotics Cell' },
];

export const mockRules: AutomationRule[] = [
    {
        id: 'r1',
        equipmentId: 'eq1', // CNC Miller
        parameter: 'Temperature',
        condition: '>',
        threshold: 80,
        triggerPriority: 'critical',
        triggerTitle: 'CRITICAL: Overheating Detected',
        triggerDescription: 'Telemetry indicated Temperature > 80°C. Auto-generated by Rule Engine.',
    }
];

export const mockUsers: User[] = [
    {
        id: 'u1',
        name: 'Alex Johnson',
        email: 'alex@gearguard.com',
        password: 'Password123!',
        role: 'admin',
        avatar: 'https://i.pravatar.cc/150?u=alex',
    },
    {
        id: 'u2',
        name: 'Sam Smith',
        email: 'sam@gearguard.com',
        password: 'Password123!',
        role: 'technician',
        avatar: 'https://i.pravatar.cc/150?u=sam',
    },
    {
        id: 'u3',
        name: 'Taylor Doe',
        email: 'taylor@gearguard.com',
        password: 'Password123!',
        role: 'viewer',
        avatar: 'https://i.pravatar.cc/150?u=taylor',
    },
];

export const mockCategories: EquipmentCategory[] = [
    { id: 'c1', name: 'Computers', responsibleId: 'u1', company: 'My Company (San Francisco)' },
    { id: 'c2', name: 'Software', responsibleId: 'u1', company: 'My Company (San Francisco)' },
    { id: 'c3', name: 'Monitors', responsibleId: 'u1', company: 'My Company (San Francisco)' },
    { id: 'c4', name: 'Machinery', responsibleId: 'u2', company: 'My Company (San Francisco)' },
];

export const mockEquipment: Equipment[] = [
    {
        id: 'eq1',
        name: 'CNC Milling Machine X500',
        serialNumber: 'CNC-X500-2023',
        category: 'Machinery',
        categoryId: 'c4',
        location: 'Production Hall, Line 3',
        status: 'active',
        healthScore: 85,
        lastMaintenance: '2023-11-15',
        nextMaintenance: '2024-02-15',
        description: 'High-precision 5-axis milling machine.',
        model: 'X500',
        manufacturer: 'IndustrialCore',
        department: 'Production',
        employeeId: 'u3', // Used By
        partnerId: 'u3',
        technicianId: 'u1', // Mitchell Admin
        teamId: 't4', // Mechanical Titans
        purchaseDate: '2022-01-15',
        warrantyExpiration: '2025-01-15',
        assignedDate: '2023-12-29',
        usedInLocation: 'Sanand',
        workCenter: 'CNC Assembly Line',
        workCenterId: 'wc2',
        oeeAvailability: 92,
        oeePerformance: 88,
        oeeQuality: 98,
    },
    {
        id: 'eq5', // New KUKA Robot
        name: 'KUKA Robot KR-100',
        serialNumber: 'KR-100-99X',
        category: 'Machinery',
        categoryId: 'c4',
        location: 'Robotics Cell',
        status: 'active',
        healthScore: 75,
        lastMaintenance: '2023-12-01',
        nextMaintenance: '2024-01-01',
        description: '6-axis industrial robot arm.',
        model: 'KR-100',
        manufacturer: 'KUKA',
        department: 'Assembly',
        teamId: 't2',
        workCenter: 'Robotics Cell',
        workCenterId: 'wc3',
        oeeAvailability: 75, // Low for demo
        oeePerformance: 95,
        oeeQuality: 99,
    },
    {
        id: 'eq2',
        name: 'Hydraulic Press HP-20T',
        serialNumber: 'HP-20T-8892',
        category: 'Machinery',
        categoryId: 'c4',
        location: 'Floor 1, Sector B',
        status: 'maintenance',
        healthScore: 25,
        lastMaintenance: '2023-10-01',
        nextMaintenance: '2024-01-01',
        description: '20-ton hydraulic press for component assembly.',
        model: 'HP-20T',
        manufacturer: 'PressMaster',
        department: 'Assembly',
        teamId: 't1',
        purchaseDate: '2021-06-10',
    },
    {
        id: 'eq3',
        name: 'Conveyor Belt System V2',
        serialNumber: 'CV-V2-1102',
        category: 'Machinery',
        categoryId: 'c4',
        location: 'Warehouse',
        status: 'active',
        healthScore: 92,
        lastMaintenance: '2023-12-10',
        nextMaintenance: '2024-06-10',
        description: 'Main automated conveyor belt for packaging.',
        model: 'V2',
        manufacturer: 'LogiTech',
        department: 'Logistics',
        teamId: 't2', // Electronics for conveyor
        purchaseDate: '2023-01-20',
    },
    {
        id: 'eq4',
        name: 'Industrial Generator G-500',
        serialNumber: 'G-500-3341',
        category: 'Utilities',
        location: 'Basement',
        status: 'retired',
        healthScore: 0,
        lastMaintenance: '2022-05-20',
        nextMaintenance: null,
        description: 'Backup diesel generator. Replaced by G-1000.',
        model: 'G-500',
        manufacturer: 'PowerGen',
    },
];

export const mockRequests: MaintenanceRequest[] = [
    {
        id: 'req1',
        equipmentId: 'eq2',
        requesterId: 'u2',
        assigneeId: 'u2',
        title: 'Hydraulic Leak Detected',
        description: 'Oil leakage observed near the main piston seal.',
        priority: 'high',
        status: 'in_progress',
        type: 'corrective',
        teamId: 't1',
        createdAt: '2023-12-20T09:00:00Z',
        updatedAt: '2023-12-21T10:00:00Z',
        scheduledDate: '2023-12-22T14:00:00Z',
    },
    {
        id: 'req2',
        equipmentId: 'eq1',
        requesterId: 'u1',
        assigneeId: undefined,
        title: 'Routine Calibration',
        description: 'Quarterly calibration of axis sensors.',
        priority: 'medium',
        status: 'new',
        type: 'preventive',
        teamId: 't1',
        createdAt: '2023-12-26T14:30:00Z',
        updatedAt: '2023-12-26T14:30:00Z',
        scheduledDate: '2024-01-05T09:00:00Z',
    },
    {
        id: 'req3',
        equipmentId: 'eq3',
        requesterId: 'u3',
        assigneeId: 'u2',
        title: 'Belt Tension Adjustment',
        description: 'Belt is slipping under heavy load.',
        priority: 'low',
        status: 'completed',
        createdAt: '2023-12-10T11:00:00Z',
        updatedAt: '2023-12-12T16:00:00Z',
        completionDate: '2023-12-12T16:00:00Z',
    },
    {
        id: 'req4',
        equipmentId: 'eq1',
        requesterId: 'u2',
        assigneeId: 'u2',
        title: 'Coolant System Check',
        description: 'Low coolant pressure warning.',
        priority: 'critical',
        status: 'pending_parts',
        createdAt: '2023-12-25T08:00:00Z',
        updatedAt: '2023-12-25T09:30:00Z',
    },
];
